# Generated by Django 5.2.5 on 2025-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_alter_article_options_alter_newsletter_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="article",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="publisher",
        ),
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
