# Generated by Django 5.2.5 on 2025-09-10 07:55
from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Codenames we want to assign
    wanted_codenames = [
        "view_article",
        "change_article",
        "delete_article",
        "add_article",
        "view_newsletter",
        "change_newsletter",
        "delete_newsletter",
        "add_newsletter",
    ]

    # Fetch only available permissions (avoids DoesNotExist)
    permissions = {
        p.codename: p
        for p in Permission.objects.filter(codename__in=wanted_codenames)
    }

    # Create Editor group
    editor_group, _ = Group.objects.get_or_create(name="Editor")
    editor_group.permissions.set(
        [
            permissions[c]
            for c in [
                "change_article",
                "delete_article",
                "view_article",
                "change_newsletter",
                "delete_newsletter",
                "view_newsletter",
            ]
            if c in permissions
        ]
    )

    # Create Journalist group
    journalist_group, _ = Group.objects.get_or_create(name="Journalist")
    journalist_group.permissions.set(
        [
            permissions[c]
            for c in [
                "add_article",
                "change_article",
                "delete_article",
                "view_article",
                "add_newsletter",
                "change_newsletter",
                "delete_newsletter",
                "view_newsletter",
            ]
            if c in permissions
        ]
    )

    # Create Reader group
    reader_group, _ = Group.objects.get_or_create(name="Reader")
    reader_group.permissions.set(
        [
            permissions[c]
            for c in ["view_article", "view_newsletter"]
            if c in permissions
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0005_profile"),
        ("archive", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
