# Generated by Django 5.2.5 on 2025-09-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_auto_20250910_0955"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="archive.publisher"
            ),
        ),
    ]
