# Generated by Django 5.2.5 on 2025-09-14 07:58
from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    wanted_codenames = [
        "view_article",
        "change_article",
        "delete_article",
        "add_article",
        "view_newsletter",
        "change_newsletter",
        "delete_newsletter",
        "add_newsletter",
    ]

    permissions = {
        p.codename: p
        for p in Permission.objects.filter(codename__in=wanted_codenames)
    }

    # Create Editor group and assign permissions
    editor_group, _ = Group.objects.get_or_create(name="Editor")
    editor_group.permissions.set(
        [
            permissions[c]
            for c in [
                "change_article",
                "delete_article",
                "view_article",
                "change_newsletter",
                "delete_newsletter",
                "view_newsletter",
            ]
            if c in permissions
        ]
    )

    # Create Journalist group and assign permissions
    journalist_group, _ = Group.objects.get_or_create(name="Journalist")
    journalist_group.permissions.set(
        [
            permissions[c]
            for c in [
                "add_article",
                "change_article",
                "delete_article",
                "view_article",
                "add_newsletter",
                "change_newsletter",
                "delete_newsletter",
                "view_newsletter",
            ]
            if c in permissions
        ]
    )

    # Create Reader group and assign permissions
    reader_group, _ = Group.objects.get_or_create(name="Reader")
    reader_group.permissions.set(
        [
            permissions[c]
            for c in ["view_article", "view_newsletter"]
            if c in permissions
        ]
    )


def create_dummy_publisher(apps, schema_editor):
    Publisher = apps.get_model("archive", "Publisher")
    # Use get_or_create to prevent duplicates on subsequent runs
    Publisher.objects.get_or_create(name="Billboard")


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0008_auto_add_approval_and_publisher"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
        migrations.RunPython(create_dummy_publisher),
    ]
